### ISSUE TITLE
👑 Epic: Recommendation System

### ISSUE THREAD

**Issue by BryanPan342** [cs130-w21/book.ar#8]
### Overview:
Produce a recommended list of titles based on an image of several books 

## User Stories

- [x] seed user info with users interests #5
- [x] Create Cloud Function for the Google Vision API #6
- [x] submit photo to get book recommendations #7

--- 
This is an 👑 Epic
